version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_SERVER_PORT}:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../projects:/var/www
    environment:
      - TZ=${TZ}

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/backend_queue.conf:/etc/supervisor/conf.d/backend_queue.conf
      - ./docker/php/backend_cron.conf:/etc/supervisor/conf.d/backend_cron.conf
      - ../projects:/var/www
    environment:
      - ENV=${ENV}

  mysql:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
    external: false