version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_FRONT_PORT}:80"
      - "${NGINX_SERVER_PORT}:3000"
    depends_on:
      - php
      - node
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../projects/backend:/var/www/server
    environment:
      - TZ=${TZ}

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/server
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../projects/backend:/var/www/server

  node:
    container_name: next_app
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    working_dir: /var/www/front
    tty: true
    ports:
      - "33000:3000"
    expose:
      - 3000
    volumes:
      - ../projects/frontend:/var/www/front
    # command: bash -c "npm install && npm run build && npm run start"
    command: bash -c "npm install && npm run dev"

  mysql:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
    external: false